config/routes.rb
Rails.application.routes.draw do
  root 'splash_screen#splash'
  get '/splash', to: 'splash_screen#splash'
  
  devise_for :users
  
  devise_scope :user do
    # root to: 'devise/sessions#new'
  end
  resources :users
  resources :groups, :path => "categories" do 
    resources :expenses, :path => "transactions"
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    user ||= User.new # guest user (not logged in)

    can :manage, Group, user_id: user.id
    can :manage, Expense, user_id: user.id
    can :manage, GroupExpense, group: { user_id: user.id }

    # cannot statements
    cannot :destroy, Group do |group|
      group.user_id != user.id
    end
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :groups, through: :group_expenses, dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 20 },
                   uniqueness: { scope: :author, message: 'You already have a transaction with this name' }
  validates :amount, presence: true, numericality: { greater_that_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 20 },
                   uniqueness: { scope: :author, message: 'You already have a category with this name' }
  validates :icon, presence: true
  def total_transactions
    expenses.sum(:amount)
  end
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/splash_screen.rb
class SplashScreen < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: :author_id, dependent: :destroy
  has_many :expenses, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:splash]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[edit update destroy]
  before_action :set_group, only: %i[index new edit create update destroy]
  before_action :set_user, only: %i[index edit create update destroy]

  # GET /expenses or /expenses.json
  def index
    @expenses = @group.expenses.order(created_at: :desc)
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET group/expenses/1/edit
  # Get an existing expense record to render the edit form
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(author: @author, **expense_params)
    if @expense.save
      @group_expense = GroupExpense.create(group: @group, expense: @expense)
      redirect_to group_expenses_url(@group), notice: 'Expense was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    if @expense.update(expense_params)
      redirect_to group_expenses_url, notice: 'Expense was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    redirect_to group_expenses_url(@group), notice: 'Expense was successfully destroyed.'
  end

  private

  def set_user
    @author = current_user
  end

  def set_group
    @group = set_user.groups.find(params[:group_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = set_user.expenses.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # Set group and user for before actions
  before_action :set_group, only: %i[edit update destroy]
  before_action :set_user, only: %i[index edit create update destroy]

  # GET /groups or /groups.json
  def index
    @groups = @author.groups
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(author: @author, **group_params)
    if @group.save
      redirect_to groups_url, notice: 'Group was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    if @group.update(group_params)
      redirect_to groups_url, notice: 'Group was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private

  # Set current user

  def set_user
    @author = current_user
  end

  # Set chosen group
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = set_user.groups.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def splash
    if current_user
      redirect_to groups_url, alert: "You are already logged in as, #{current_user.name}"
    else
      render :splash
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :redirect_to_categories, only: %i[show index]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def redirect_to_categories
    redirect_to groups_url
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/helpers/splash_screens_helper.rb
require 'rails_helper'

RSpec.describe "SplashScreens", type: :request do
  describe "GET /index" do
    it "returns http success" do
      get "/splash_screen/index"
      expect(response).to have_http_status(:success)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_expense.html.erb
<div class="card my-5">
  <div class="card-body d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center gap-3">
      <div class="d-flex align-items-center gap-2">
        <%= image_tag @group.icon, class: "category-images" %>
        <div>
          <h5 class="card-title"><%= expense.name %></h5>
          <span class="card-text font-bold">$<%= expense.amount %></span>
        </div>
      </div>
    </div>
    <% if action_name != "show" %>
      <div class="d-flex gap-2">
        <%= link_to edit_group_expense_path(@group,expense), class: "btn btn-sm btn-outline-secondary" do %>
          <i class="bi bi-pencil-square"></i>
        <% end %>
        <%= button_to group_expense_path(@group, expense), method: :delete, class: "btn btn-sm btn-outline-danger" do %>
          <i class="bi bi-trash"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/expenses/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: expense, url: "#{action_name == 'edit' ? group_expense_path(@group, expense) : group_expenses_path(@group)}", class: "contents") do |form| %>
    <% if expense.errors.any? %>
      <div id="error_explanation" class="bg-danger text-white px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

        <ul>
          <% expense.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="my-5">
      <%= form.label :amount, class: "form-label" %>
      <%= form.number_field :amount, step: ".01", class: "form-control" %>
    </div>

    <div class="mb-3 d-flex justify-content-center">
      <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}", class: "new-category btn btn-light" %>
    </div>
  <% end %>
</div>

<div class="d-flex fixed-bottom py-3 px-2" style="background-color: #60B524;">
  <div class="container d-flex justify-content-center category-container">
    <%= link_to groups_path, class: "back to category" do %>
      <p style="color: #fff;">Back to Categories</p>
    <% end %>
  </div>
</div>

<div class="d-flex fixed-bottom py-3 px-2" style="background-color: #6c757d;">
  <div class="container d-flex justify-content-center category-container">
    <%= link_to group_expenses_path(@group), class: "category", style: 'text-decoration: none' do %>
      <p style="color: #fff;">Back to Transactions</p>
    <% end %>
  </div>
</div>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<div>|
  <%= link_to "Back to expenses", group_expenses_path %>
</div>

app/views/expenses/index.html.erb
<div class="container">
  <div id="expenses" class="expense-container">
    <%= render @expenses %>
  </div>
</div>

<div class="bg-secondary fixed-bottom d-flex justify-content-center py-3">
  <%= link_to new_group_expense_path, class: "w-75 d-flex align-items-center justify-content-center gap-2 py-2 px-5 bg-secondary border text-white block font-medium" do %>
    <span>New transaction</span>
  <% end %>
</div>

app/views/expenses/new.html.erb
<%= render "form", expense: @expense %>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>

app/views/groups/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: group, class: "contents") do |form| %>
    <% if group.errors.any? %>
      <div id="error_explanation" class="bg-danger text-white px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :icon, class: "form-label" %>
      <%= form.text_field :icon, class: "form-control" %>
    </div>

    <div class="mb-3 d-flex justify-content-center">
      <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}", class: "new-category btn btn-light" %>
    </div>
  <% end %>
</div>

<div class="d-flex fixed-bottom py-3 px-2" style="background-color: #60B524;">
  <div class="container d-flex justify-content-center category-container">
    <%= link_to groups_path, class: "back to category", style: 'text-decoration: none' do %>
      <p style="color: #fff;">Back to Categories</p>
    <% end %>
  </div>
</div>

app/views/groups/_group.html.erb
<%= link_to  group_expenses_path(group), class: "w-100", style: 'text-decoration: none; font-family: \'Proxima Nova\', sans-serif; color: #828282; ' do %>
<div id="<%= dom_id group %>" class="card d-flex flex-column justify-content-between align-items-center">
  <div class="w-100 gap-4 d-flex align-items-center justify-content-space-between p-2">
    <%= image_tag group.icon, class: 'category-images'%>
    <div class="flex-grow-1 text-center">
      <h5 class="card-title text-start"><%= group.name %></h5>
    </div>
    <div class="flex-grow-0 font-weight-bold">
      <p class="card-text" style="color: blacl"><strong>$<%= group.total_transactions %></strong></p>
    </div>
  </div>

    <% if action_name != "show" %>
    <div class="d-flex gap-2 align-self-start pb-2">
    <%= link_to edit_group_path(group), class: "btn btn-outline-secondary btn-sm", 'data-turbolinks': false do %>
      Edit
    <% end %>
    <%= button_to group_path(group), method: :delete, class: "btn btn-outline-secondary btn-sm", 'data-turbolinks': false, data: { confirm: 'Are you sure?' } do %>
      Delete
    <% end %>
    </div>
  <% end %>
</div>
    <%end%>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div id="groups" class=" group-container mt-3 d-flex gap-2 flex-column overflow-y-scroll">
        <%= render @groups %>
      </div>
    </div>
  </div>
</div>

<div class="d-flex fixed-bottom py-3 px-2" style="background-color: #60B524;">
  <div class="container d-flex justify-content-center category-container">
    <%= link_to new_group_path, class: "new-category" do %>
      <p style="color: #fff;">New Category</p>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# Bootstrap Links %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <%#Fonts Cdn Links %>
    <link href="https://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
  </head>

  <body>
  <% if current_user %>
  <%= render 'shared/header'%>
  <%end %>
   <main class="container mx-auto">
  <% if notice.present? %>
    <div class="alert alert-success alert-dismissible fade show floating-notice" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% elsif alert.present? %>
    <div class="alert alert-danger alert-dismissible fade show floating-notice" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
    </main>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary px-3" style="background-color: #316caf !important">
  <% if controller_name != 'groups' %>
    <a class="navbar-brand" href="<%= groups_path %>">
      <i class="bi bi-arrow-left"></i>
    </a>
  <% end %>
  <h1 class="navbar-brand mb-0 mx-auto text-white text-uppercase">
    <% if controller_name == 'expenses' %>
      <%= 'Transactions' %>
    <% else %>
      <%= 'Categories' %>
    <% end %>
  </h1>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= button_to 'SIGN OUT', destroy_user_session_path, method: :delete, data: {turbo: false}, class: 'btn btn-outline-light' %>
      </li>
    </ul>
  </div>
</nav>

app/views/splash_screen/splash.html.erb
<div class="d-flex flex-column align-items-center justify-content-end vh-100">
  <div class="d-flex justify-content-center align-items-center mb-3 flex-grow-1">
    <%= image_tag 'snapscan-logo.png', class: 'img-fluid' %>
  </div>
  <div class="form-container d-grid gap-2 mb-3 w-100 px-5">
    <%= link_to new_user_session_path, class: 'btn btn-primary' do %>
      Log In
    <% end %>
    <%= link_to new_user_registration_path, class: 'btn btn-secondary' do %>
      Register
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>